apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8sannotationdenylabel
spec:
  crd:
    spec:
      names:
        kind: K8sAnnotationDenyLabel
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          properties:
            annotations:
              type: array
              items:
                type: object
                properties:
                  key:
                    type: string
                  value:
                    type: string
                  label:
                    type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sannotationdenylabel

        violation[{"msg": msg}] {
          value := input.review.object.metadata.annotations[key]
          getlabel := input.review.object.metadata.labels[label]
          denyval := input.parameters.annotations[_]
          denyval.key == key
          denyval.label == label
          { value == denyval.value }
          { getlabel == denyval.label }
          msg := sprintf("Annotation <%v: %v> is not allowed with label %v", [key, value, denyval.label])
        }
